# Generated by Django 2.2 on 2020-10-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountgames',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
