# Generated by Django 2.2 on 2020-10-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_discountgames_old_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountgames',
            options={'verbose_name': 'игра со скидкой', 'verbose_name_plural': 'игры со скидкой'},
        ),
    ]
