# Generated by Django 2.2 on 2020-10-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201002_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategories',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
    ]
