# Generated by Django 2.2 on 2020-10-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_gamecategories_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
        migrations.AddField(
            model_name='discountgames',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
        migrations.AddField(
            model_name='games',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
    ]
