# Generated by Django 2.2 on 2020-10-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201012_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
