# Generated by Django 2.2 on 2020-10-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_games_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.ImageField(blank=True, upload_to='game_images'),
        ),
    ]
