# Generated by Django 2.2 on 2020-10-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20201014_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecategories',
            name='name',
            field=models.CharField(help_text='категории игр<br>представленных на нашем сайте', max_length=64, unique=True, verbose_name='название категории'),
        ),
    ]
