# Generated by Django 2.2 on 2020-10-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20201020_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='categories',
            field=models.CharField(choices=[(None, 'Выберите категорию'), ('a', 'action'), ('s', 'shooter'), ('f', 'fighting')], default='Some category', max_length=1),
        ),
    ]
