# Generated by Django 2.2 on 2020-10-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_games_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='categories',
        ),
    ]
