# Generated by Django 2.2 on 2020-10-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['-add_datetime']},
        ),
    ]
