# Generated by Django 2.2 on 2020-10-27 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20201027_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 27, 12, 54, 3, 489265, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 12, 54, 3, 489265, tzinfo=utc)),
        ),
    ]
