# Generated by Django 2.2 on 2021-03-10 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_auto_20210111_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 15, 58, 44, 778159, tzinfo=utc)),
        ),
    ]
