# Generated by Django 2.2 on 2021-03-31 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_auto_20210331_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 14, 49, 38, 816204, tzinfo=utc)),
        ),
    ]
