# Generated by Django 2.2 on 2021-04-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_auto_20210423_1445'),
        ('authapp', '0024_auto_20210331_1849'),
    ]

    operations = [
    ]
